# Google Cloud Build configuration for Apartment Rental Portal
# This builds and deploys both frontend and backend to Cloud Run

substitutions:
  _REGION: us-central1
  _BACKEND_SERVICE: apartment-backend
  _FRONTEND_SERVICE: apartment-frontend

steps:
  # Build Backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest'
      - '-f'
      - 'backend/Dockerfile.cloudrun'
      - 'backend'
    id: 'build-backend'

  # Build Frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:latest'
      - '-f'
      - 'frontend/Dockerfile.cloudrun'
      - 'frontend'
    id: 'build-frontend'

  # Push Backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push Frontend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},JWT_SECRET_KEY=${_JWT_SECRET_KEY}'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Get Backend URL and Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe ${_BACKEND_SERVICE} --region=${_REGION} --format='value(status.url)')
        gcloud run deploy ${_FRONTEND_SERVICE} \
          --image gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "BACKEND_URL=$BACKEND_URL" \
          --memory 256Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10
    id: 'deploy-frontend'
    waitFor: ['deploy-backend', 'push-frontend']

images:
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest'
  - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
